version: '2'
services:
  cmms-db:
    build: .
    restart: always
    environment:
      MYSQL_DATABASE: fieldservice
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    ports:
    - 3306:3306 